#!/usr/bin/env python3
"""Generate the C++ and C# protocol codecs and the golden byte vectors from Protocol/schema/protocol.toml.

Usage:  python Protocol/generator/gen.py           (writes all outputs)
        python Protocol/generator/gen.py --check   (exit 1 if any output is stale; use in CI)

Standard library only (Python 3.11+ for tomllib).
"""
from __future__ import annotations

import json
import re
import struct
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "Protocol" / "schema" / "protocol.toml"

OUT_CPP_HPP = ROOT / "Server" / "libs" / "protocol" / "include" / "waw" / "protocol" / "generated" / "messages.hpp"
OUT_CPP_CPP = ROOT / "Server" / "libs" / "protocol" / "src" / "generated" / "messages.cpp"
OUT_CPP_GOLDEN = ROOT / "Server" / "tests" / "generated" / "golden_samples.hpp"
OUT_CS = ROOT / "WaW" / "Assets" / "Scripts" / "Protocol" / "Generated" / "Messages.cs"
OUT_CS_GOLDEN = ROOT / "WaW" / "Assets" / "Tests" / "EditMode" / "Protocol" / "Generated" / "GoldenSamples.cs"
OUT_VECTORS = ROOT / "Protocol" / "vectors" / "golden.json"

HEADER = "// <auto-generated> by Protocol/generator/gen.py from Protocol/schema/protocol.toml - DO NOT EDIT </auto-generated>\n"

PRIMS = {
    # name: (struct fmt, C++ type, C# type, C# writer/reader suffix)
    "u8": ("<B", "std::uint8_t", "byte", "U8"),
    "u16": ("<H", "std::uint16_t", "ushort", "U16"),
    "u32": ("<I", "std::uint32_t", "uint", "U32"),
    "u64": ("<Q", "std::uint64_t", "ulong", "U64"),
    "i8": ("<b", "std::int8_t", "sbyte", "I8"),
    "i16": ("<h", "std::int16_t", "short", "I16"),
    "i32": ("<i", "std::int32_t", "int", "I32"),
    "i64": ("<q", "std::int64_t", "long", "I64"),
    "f32": ("<f", "float", "float", "F32"),
    "f64": ("<d", "double", "double", "F64"),
    "bool": ("<B", "bool", "bool", "Bool"),
    "string": (None, "std::string", "string", "String"),
}
INT_RANGES = {
    "u8": (0, 0xFF), "u16": (0, 0xFFFF), "u32": (0, 0xFFFFFFFF), "u64": (0, 0xFFFFFFFFFFFFFFFF),
    "i8": (-0x80, 0x7F), "i16": (-0x8000, 0x7FFF), "i32": (-0x80000000, 0x7FFFFFFF), "i64": (-(1 << 63), (1 << 63) - 1),
}


# ------------------------------------------------------------------------------------------------ model

@dataclass
class Field:
    name: str
    type: str          # base type without '?' and without list<>
    is_list: bool
    optional: bool


@dataclass
class Composite:
    name: str
    fields: list[Field]
    doc: str = ""
    msg_id: int | None = None
    direction: str | None = None   # "c2s" / "s2c" for messages

    @property
    def has_optional(self) -> bool:
        return any(f.optional for f in self.fields)


@dataclass
class Enum:
    name: str
    type: str
    values: list[tuple[str, int]]


def parse_field(name: str, spec: str) -> Field:
    optional = spec.endswith("?")
    if optional:
        spec = spec[:-1]
    m = re.fullmatch(r"list<(\w+)>", spec)
    if m:
        return Field(name, m.group(1), True, optional)
    return Field(name, spec, False, optional)


def load_schema(path: Path):
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    meta = data["meta"]
    enums = [Enum(e["name"], e["type"], [(n, v) for n, v in e["values"]]) for e in data.get("enum", [])]
    structs = [Composite(s["name"], [parse_field(n, t) for n, t in s["fields"]], s.get("doc", "")) for s in data.get("struct", [])]
    messages = [Composite(m["name"], [parse_field(n, t) for n, t in m["fields"]], m.get("doc", ""), m["id"], m["dir"])
                for m in data.get("message", [])]
    validate(enums, structs, messages)
    return meta, enums, structs, messages


def validate(enums, structs, messages):
    names = set()
    for item in [*enums, *structs, *messages]:
        if item.name in names:
            raise SystemExit(f"duplicate type name {item.name}")
        names.add(item.name)
    enum_names = {e.name for e in enums}
    struct_names = {s.name for s in structs}
    for e in enums:
        if e.type not in INT_RANGES or e.type.startswith("i"):
            raise SystemExit(f"enum {e.name}: underlying type must be unsigned, got {e.type}")
        seen = set()
        for n, v in e.values:
            if v in seen:
                raise SystemExit(f"enum {e.name}: duplicate value {v}")
            seen.add(v)
    ids = set()
    for m in messages:
        if m.direction not in ("c2s", "s2c"):
            raise SystemExit(f"message {m.name}: dir must be c2s or s2c")
        if not (0 < m.msg_id < 0xFFFF) or m.msg_id in ids:
            raise SystemExit(f"message {m.name}: bad or duplicate id {m.msg_id}")
        ids.add(m.msg_id)
    defined = set()
    for c in [*structs, *messages]:
        opt = sum(1 for f in c.fields if f.optional)
        if opt > 32:
            raise SystemExit(f"{c.name}: more than 32 optional fields")
        for f in c.fields:
            if f.type not in PRIMS and f.type not in enum_names and f.type not in struct_names:
                raise SystemExit(f"{c.name}.{f.name}: unknown type {f.type}")
            if f.type in struct_names and f.type not in defined and c.msg_id is None:
                raise SystemExit(f"{c.name}.{f.name}: struct {f.type} must be declared before use")
        if c.msg_id is None:
            defined.add(c.name)


def snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def pascal(name: str) -> str:
    return name[0].upper() + name[1:]


# ------------------------------------------------------------------------------------------------ samples + reference encoder

class Ctx:
    def __init__(self, enums, structs):
        self.enums = {e.name: e for e in enums}
        self.structs = {s.name: s for s in structs}


def sample_scalar(ctx: Ctx, t: str, seed: int):
    if t in INT_RANGES:
        lo, hi = INT_RANGES[t]
        if lo < 0:
            return -((seed * 37 + 3) % (-lo))
        span = hi + 1
        if t == "u64":
            return (0x0102030405060708 * (seed + 1)) % span
        if t == "u32":
            return (0x01020304 * (seed + 1) + seed) % span
        return (seed * 37 + 5) % span
    if t in ("f32", "f64"):
        return float(seed) + 0.5 if seed % 2 else -(float(seed) + 0.25)
    if t == "bool":
        return seed % 2 == 0
    if t == "string":
        return f"s{seed}-é✓"
    if t in ctx.enums:
        vals = ctx.enums[t].values
        return vals[seed % len(vals)][0]
    if t in ctx.structs:
        return sample_composite(ctx, ctx.structs[t], seed)
    raise AssertionError(t)


def sample_field(ctx: Ctx, f: Field, seed: int, opt_index: int):
    if f.optional and (seed + opt_index) % 2 == 1:
        return None
    if f.is_list:
        return [sample_scalar(ctx, f.type, seed * 3 + k + 1) for k in range(2)]
    return sample_scalar(ctx, f.type, seed)


def sample_composite(ctx: Ctx, c: Composite, seed: int):
    out = {}
    opt_index = 0
    for i, f in enumerate(c.fields):
        out[f.name] = sample_field(ctx, f, seed * 7 + i + 1, opt_index)
        if f.optional:
            opt_index += 1
    return out


def encode_scalar(ctx: Ctx, t: str, v) -> bytes:
    if t == "string":
        b = v.encode("utf-8")
        return struct.pack("<H", len(b)) + b
    if t == "bool":
        return struct.pack("<B", 1 if v else 0)
    if t in PRIMS:
        return struct.pack(PRIMS[t][0], v)
    if t in ctx.enums:
        e = ctx.enums[t]
        return struct.pack(PRIMS[e.type][0], dict(e.values)[v])
    return encode_composite(ctx, ctx.structs[t], v)


def encode_composite(ctx: Ctx, c: Composite, value: dict) -> bytes:
    out = b""
    if c.has_optional:
        mask, bit = 0, 0
        for f in c.fields:
            if f.optional:
                if value[f.name] is not None:
                    mask |= 1 << bit
                bit += 1
        out += struct.pack("<I", mask)
    for f in c.fields:
        v = value[f.name]
        if f.optional and v is None:
            continue
        if f.is_list:
            out += struct.pack("<H", len(v)) + b"".join(encode_scalar(ctx, f.type, x) for x in v)
        else:
            out += encode_scalar(ctx, f.type, v)
    return out


# ------------------------------------------------------------------------------------------------ C++

def cpp_type(ctx: Ctx, f: Field) -> str:
    base = PRIMS[f.type][1] if f.type in PRIMS else f.type
    if f.is_list:
        base = f"std::vector<{base}>"
    if f.optional:
        base = f"std::optional<{base}>"
    return base


def cpp_string_literal(s: str) -> str:
    parts, cur = [], ""
    for byte in s.encode("utf-8"):
        if 0x20 <= byte < 0x7F and chr(byte) not in '"\\':
            cur += chr(byte)
        else:
            if cur:
                parts.append(cur)
                cur = ""
            parts.append(f"\\x{byte:02X}")
    if cur:
        parts.append(cur)
    # Separate every chunk so a hex escape is never followed by a hex digit.
    return "std::string(" + " ".join(f'"{p}"' for p in parts) + ")" if parts else 'std::string()'


def cpp_scalar_literal(ctx: Ctx, t: str, v) -> str:
    if t == "string":
        return cpp_string_literal(v)
    if t == "bool":
        return "true" if v else "false"
    if t == "f32":
        return f"{v!r}f"
    if t == "f64":
        return repr(v)
    if t in INT_RANGES:
        if t == "i64" and v == INT_RANGES[t][0]:
            return "INT64_MIN"
        suffix = {"u64": "ull", "i64": "ll", "u32": "u"}.get(t, "")
        return f"static_cast<{PRIMS[t][1]}>({v}{suffix})"
    if t in ctx.enums:
        return f"{t}::{v}"
    c = ctx.structs[t]
    return cpp_composite_literal(ctx, c, v)


def cpp_field_literal(ctx: Ctx, f: Field, v) -> str:
    if v is None:
        return "std::nullopt"
    if f.is_list:
        inner = PRIMS[f.type][1] if f.type in PRIMS else f.type
        return f"std::vector<{inner}>{{" + ", ".join(cpp_scalar_literal(ctx, f.type, x) for x in v) + "}"
    return cpp_scalar_literal(ctx, f.type, v)


def cpp_composite_literal(ctx: Ctx, c: Composite, value: dict) -> str:
    inits = ", ".join(f".{snake(f.name)} = {cpp_field_literal(ctx, f, value[f.name])}" for f in c.fields)
    return f"{c.name}{{{inits}}}"


def gen_cpp(meta, enums, structs, messages):
    ctx = Ctx(enums, structs)
    h = [HEADER, "#pragma once\n",
         "#include <cstdint>", "#include <expected>", "#include <optional>", "#include <span>", "#include <string>",
         "#include <string_view>", "#include <variant>", "#include <vector>", "",
         '#include "waw/protocol/bytes.hpp"', "", "namespace waw::protocol {", "",
         f"inline constexpr std::uint32_t kProtocolVersion = {meta['protocol_version']};",
         f"inline constexpr std::uint32_t kMaxPayloadBytes = {meta['max_payload_bytes']};", ""]
    # enums
    for e in enums:
        h.append(f"enum class {e.name} : {PRIMS[e.type][1]} {{")
        h += [f"    {n} = {v}," for n, v in e.values]
        h.append("};")
        h.append(f"[[nodiscard]] bool is_valid({e.name} value) noexcept;")
        h.append(f"[[nodiscard]] std::string_view to_string({e.name} value) noexcept;")
        h.append("")
    h.append("enum class MessageId : std::uint16_t {")
    h += [f"    {m.name} = {m.msg_id}," for m in messages]
    h.append("};")
    h.append("[[nodiscard]] std::string_view message_name(std::uint16_t id) noexcept;")
    h.append("")

    def emit_composite(c: Composite):
        if c.doc:
            h.append(f"/// {c.doc}")
        h.append(f"struct {c.name} {{")
        if c.msg_id is not None:
            h.append(f"    static constexpr MessageId kId = MessageId::{c.name};")
        for f in c.fields:
            h.append(f"    {cpp_type(ctx, f)} {snake(f.name)}{{}};")
        h.append(f"    friend bool operator==(const {c.name}&, const {c.name}&) = default;")
        h.append("};")
        h.append(f"void encode(ByteWriter& w, const {c.name}& v);")
        h.append(f"[[nodiscard]] bool decode(ByteReader& r, {c.name}& v);")
        h.append("")

    for s in structs:
        emit_composite(s)
    for m in messages:
        emit_composite(m)

    c2s = [m for m in messages if m.direction == "c2s"]
    s2c = [m for m in messages if m.direction == "s2c"]
    h.append("using ClientMessage = std::variant<" + ", ".join(m.name for m in c2s) + ">;")
    h.append("using ServerMessage = std::variant<" + ", ".join(m.name for m in s2c) + ">;")
    h.append("")
    h.append("enum class DecodeError : std::uint8_t { UnknownMessage, WrongDirection, Malformed, TrailingBytes };")
    h.append("[[nodiscard]] std::string_view to_string(DecodeError e) noexcept;")
    h.append("/// Decode one payload sent by a client (server side).")
    h.append("[[nodiscard]] std::expected<ClientMessage, DecodeError> decode_client_message(std::uint16_t id, std::span<const std::uint8_t> payload);")
    h.append("/// Decode one payload sent by the server (client side / tests).")
    h.append("[[nodiscard]] std::expected<ServerMessage, DecodeError> decode_server_message(std::uint16_t id, std::span<const std::uint8_t> payload);")
    h.append("")
    h.append("/// Message id of any message held in a variant.")
    h.append("[[nodiscard]] MessageId message_id(const ClientMessage& m) noexcept;")
    h.append("[[nodiscard]] MessageId message_id(const ServerMessage& m) noexcept;")
    h.append("")
    h.append("}  // namespace waw::protocol")
    hpp = "\n".join(h) + "\n"

    c = [HEADER, '#include "waw/protocol/generated/messages.hpp"', "", "#include <type_traits>", "#include <utility>", "", "namespace waw::protocol {", ""]
    for e in enums:
        c.append(f"bool is_valid({e.name} value) noexcept {{")
        c.append("    switch (value) {")
        c += [f"        case {e.name}::{n}:" for n, _ in e.values]
        c.append("            return true;")
        c.append("    }")
        c.append("    return false;")
        c.append("}")
        c.append(f"std::string_view to_string({e.name} value) noexcept {{")
        c.append("    switch (value) {")
        c += [f'        case {e.name}::{n}: return "{n}";' for n, _ in e.values]
        c.append("    }")
        c.append('    return "?";')
        c.append("}")
        c.append(f"static void encode(ByteWriter& w, {e.name} v) {{ w.write(static_cast<{PRIMS[e.type][1]}>(v)); }}")
        c.append(f"static bool decode(ByteReader& r, {e.name}& v) {{")
        c.append(f"    {PRIMS[e.type][1]} raw{{}};")
        c.append(f"    if (!r.read(raw)) return false;")
        c.append(f"    v = static_cast<{e.name}>(raw);")
        c.append(f"    return is_valid(v);")
        c.append("}")
        c.append("")
    c.append("std::string_view message_name(std::uint16_t id) noexcept {")
    c.append("    switch (id) {")
    c += [f'        case {m.msg_id}: return "{m.name}";' for m in messages]
    c.append("    }")
    c.append('    return "Unknown";')
    c.append("}")
    c.append("")
    c.append("std::string_view to_string(DecodeError e) noexcept {")
    c.append("    switch (e) {")
    for n in ("UnknownMessage", "WrongDirection", "Malformed", "TrailingBytes"):
        c.append(f'        case DecodeError::{n}: return "{n}";')
    c.append("    }")
    c.append('    return "?";')
    c.append("}")
    c.append("")

    def emit_codec(comp: Composite):
        var = snake(comp.name)
        c.append(f"void encode(ByteWriter& w, const {comp.name}& v) {{")
        if comp.has_optional:
            c.append("    std::uint32_t mask = 0;")
            bit = 0
            for f in comp.fields:
                if f.optional:
                    c.append(f"    if (v.{snake(f.name)}) mask |= (1u << {bit});")
                    bit += 1
            c.append("    w.write(mask);")
        for f in comp.fields:
            acc = f"v.{snake(f.name)}"
            if f.optional:
                c.append(f"    if ({acc}) {{")
                acc = f"*{acc}"
                ind = "        "
            else:
                ind = "    "
            if f.is_list:
                c.append(f"{ind}encode_list(w, {acc}, [](ByteWriter& lw, const auto& e) {{ encode(lw, e); }});")
            else:
                c.append(f"{ind}encode(w, {acc});")
            if f.optional:
                c.append("    }")
        if not comp.fields:
            c.append("    (void)w;")
            c.append("    (void)v;")
        c.append("}")
        c.append(f"bool decode(ByteReader& r, {comp.name}& v) {{")
        if comp.has_optional:
            c.append("    std::uint32_t mask = 0;")
            c.append("    if (!r.read(mask)) return false;")
            nopt = sum(1 for f in comp.fields if f.optional)
            if nopt < 32:
                c.append(f"    if (mask >> {nopt}) return false;  // unknown optional bits")
        bit = 0
        for f in comp.fields:
            target = f"v.{snake(f.name)}"
            ind = "    "
            if f.optional:
                c.append(f"    {target}.reset();")
                c.append(f"    if (mask & (1u << {bit})) {{")
                c.append(f"        {target}.emplace();")
                target = f"*{target}"
                ind = "        "
                bit += 1
            if f.is_list:
                c.append(f"{ind}if (!decode_list(r, {target}, [](ByteReader& lr, auto& e) {{ return decode(lr, e); }})) return false;")
            else:
                c.append(f"{ind}if (!decode(r, {target})) return false;")
            if f.optional:
                c.append("    }")
        if not comp.fields:
            c.append("    (void)v;")
        c.append("    return !r.fail();")
        c.append("}")
        c.append("")

    for s in structs:
        emit_codec(s)
    for m in messages:
        emit_codec(m)

    for side, own, other, fn in (("Client", c2s, s2c, "decode_client_message"), ("Server", s2c, c2s, "decode_server_message")):
        c.append(f"std::expected<{side}Message, DecodeError> {fn}(std::uint16_t id, std::span<const std::uint8_t> payload) {{")
        c.append("    ByteReader r(payload);")
        c.append("    switch (id) {")
        for m in own:
            c.append(f"        case {m.msg_id}: {{")
            c.append(f"            {m.name} msg;")
            c.append("            if (!decode(r, msg)) return std::unexpected(DecodeError::Malformed);")
            c.append("            if (r.remaining() != 0) return std::unexpected(DecodeError::TrailingBytes);")
            c.append(f"            return {side}Message{{std::move(msg)}};")
            c.append("        }")
        for m in other:
            c.append(f"        case {m.msg_id}:")
        if other:
            c.append("            return std::unexpected(DecodeError::WrongDirection);")
        c.append("        default:")
        c.append("            return std::unexpected(DecodeError::UnknownMessage);")
        c.append("    }")
        c.append("}")
        c.append("")
        c.append(f"MessageId message_id(const {side}Message& m) noexcept {{")
        c.append("    return std::visit([](const auto& msg) { return std::remove_cvref_t<decltype(msg)>::kId; }, m);")
        c.append("}")
        c.append("")
    c.append("}  // namespace waw::protocol")
    cpp = "\n".join(c) + "\n"
    return hpp, cpp


def gen_cpp_golden(ctx: Ctx, samples):
    g = [HEADER, "#pragma once", "", "#include <functional>", "#include <string_view>", "#include <vector>", "",
         '#include "waw/protocol/generated/messages.hpp"', "", "namespace waw::protocol::golden {", "",
         "struct Sample {", "    std::string_view name;", "    std::uint16_t id;", "    bool client_to_server;",
         "    std::string_view hex;", "    std::function<std::vector<std::uint8_t>()> encode_sample;",
         "    std::function<bool(std::span<const std::uint8_t>)> decodes_to_sample;", "};", "",
         "inline std::vector<Sample> all_samples() {", "    std::vector<Sample> out;"]
    for m, value, hexstr in samples:
        lit = cpp_composite_literal(ctx, m, value)
        side = "client" if m.direction == "c2s" else "server"
        g.append("    {")
        g.append(f"        auto make = [] {{ return {lit}; }};")
        g.append(f'        out.push_back(Sample{{"{m.name}", {m.msg_id}, {"true" if m.direction == "c2s" else "false"}, "{hexstr}",')
        g.append("            [make] { ByteWriter w; encode(w, make()); return w.take(); },")
        g.append(f"            [make](std::span<const std::uint8_t> p) {{ auto d = decode_{side}_message({m.msg_id}, p);")
        g.append(f"                return d.has_value() && std::holds_alternative<{m.name}>(*d) && std::get<{m.name}>(*d) == make(); }}}});")
        g.append("    }")
    g += ["    return out;", "}", "", "}  // namespace waw::protocol::golden"]
    return "\n".join(g) + "\n"


# ------------------------------------------------------------------------------------------------ C#

def cs_base(ctx: Ctx, t: str) -> str:
    return PRIMS[t][2] if t in PRIMS else t


def cs_type(ctx: Ctx, f: Field) -> str:
    base = cs_base(ctx, f.type)
    if f.is_list:
        base = f"List<{base}>"
    if f.optional and (f.is_list or f.type == "string" or f.type in ctx.structs):
        return base  # reference type: null = absent
    if f.optional:
        return base + "?"
    return base


def cs_is_value_type(ctx: Ctx, f: Field) -> bool:
    return not f.is_list and f.type != "string" and f.type not in ctx.structs


def cs_write_scalar(ctx: Ctx, t: str, expr: str) -> str:
    if t in PRIMS:
        return f"w.Write{PRIMS[t][3]}({expr});"
    if t in ctx.enums:
        return f"w.Write{PRIMS[ctx.enums[t].type][3]}(({PRIMS[ctx.enums[t].type][2]}){expr});"
    return f"{expr}.Write(w);"


def cs_read_scalar(ctx: Ctx, t: str) -> str:
    if t in PRIMS:
        return f"r.Read{PRIMS[t][3]}()"
    if t in ctx.enums:
        return f"ProtocolEnums.Check{t}(r.Read{PRIMS[ctx.enums[t].type][3]}())"
    return f"{t}.Read(r)"


def cs_scalar_literal(ctx: Ctx, t: str, v) -> str:
    if t == "string":
        out = '"'
        for ch in v:
            out += ch if 0x20 <= ord(ch) < 0x7F and ch not in '"\\' else f"\\u{ord(ch):04x}"
        return out + '"'
    if t == "bool":
        return "true" if v else "false"
    if t == "f32":
        return f"{v!r}f"
    if t == "f64":
        return f"{v!r}d"
    if t in INT_RANGES:
        if t == "i64" and v == INT_RANGES[t][0]:
            return "long.MinValue"
        if t == "i32" and v == INT_RANGES[t][0]:
            return "int.MinValue"
        suffix = {"u64": "UL", "i64": "L", "u32": "U"}.get(t, "")
        return f"({PRIMS[t][2]})({v}{suffix})"
    if t in ctx.enums:
        return f"{t}.{v}"
    return cs_composite_literal(ctx, ctx.structs[t], v)


def cs_field_literal(ctx: Ctx, f: Field, v) -> str:
    if v is None:
        return "null"
    if f.is_list:
        return f"new List<{cs_base(ctx, f.type)}> {{ " + ", ".join(cs_scalar_literal(ctx, f.type, x) for x in v) + " }"
    return cs_scalar_literal(ctx, f.type, v)


def cs_composite_literal(ctx: Ctx, c: Composite, value: dict) -> str:
    inits = ", ".join(f"{pascal(f.name)} = {cs_field_literal(ctx, f, value[f.name])}" for f in c.fields)
    return f"new {c.name} {{ {inits} }}"


def gen_cs(meta, enums, structs, messages):
    ctx = Ctx(enums, structs)
    o = [HEADER, "#nullable disable", "using System;", "using System.Collections.Generic;", "", "namespace WaW.Protocol", "{"]
    o.append("    public static class ProtocolInfo")
    o.append("    {")
    o.append(f"        public const uint ProtocolVersion = {meta['protocol_version']};")
    o.append(f"        public const int MaxPayloadBytes = {meta['max_payload_bytes']};")
    o.append("    }")
    o.append("")
    for e in enums:
        o.append(f"    public enum {e.name} : {PRIMS[e.type][2]}")
        o.append("    {")
        o += [f"        {n} = {v}," for n, v in e.values]
        o.append("    }")
        o.append("")
    o.append("    public enum MessageId : ushort")
    o.append("    {")
    o += [f"        {m.name} = {m.msg_id}," for m in messages]
    o.append("    }")
    o.append("")
    o.append("    public static class ProtocolEnums")
    o.append("    {")
    for e in enums:
        u = PRIMS[e.type][2]
        o.append(f"        public static {e.name} Check{e.name}({u} raw)")
        o.append("        {")
        o.append("            switch (raw)")
        o.append("            {")
        o.append("                case " + ": case ".join(str(v) for _, v in e.values) + ":")
        o.append(f"                    return ({e.name})raw;")
        o.append("                default:")
        o.append(f'                    throw new ProtocolException("invalid {e.name} value " + raw);')
        o.append("            }")
        o.append("        }")
    o.append("    }")
    o.append("")

    def emit(c: Composite):
        if c.doc:
            o.append(f"    /// <summary>{c.doc}</summary>")
        iface = " : IMessage" if c.msg_id is not None else ""
        o.append(f"    public sealed class {c.name}{iface}")
        o.append("    {")
        if c.msg_id is not None:
            o.append(f"        public MessageId Id => MessageId.{c.name};")
        for f in c.fields:
            o.append(f"        public {cs_type(ctx, f)} {pascal(f.name)};")
        o.append("")
        o.append("        public void Write(ByteWriter w)")
        o.append("        {")
        if c.has_optional:
            o.append("            uint mask = 0;")
            bit = 0
            for f in c.fields:
                if f.optional:
                    cond = f"{pascal(f.name)}.HasValue" if cs_is_value_type(ctx, f) else f"{pascal(f.name)} != null"
                    o.append(f"            if ({cond}) mask |= 1u << {bit};")
                    bit += 1
            o.append("            w.WriteU32(mask);")
        for f in c.fields:
            name = pascal(f.name)
            ind = "            "
            if f.optional:
                cond = f"{name}.HasValue" if cs_is_value_type(ctx, f) else f"{name} != null"
                o.append(f"            if ({cond})")
                o.append("            {")
                ind = "                "
                expr = f"{name}.Value" if cs_is_value_type(ctx, f) else name
            else:
                expr = name
            if f.is_list:
                o.append(f"{ind}w.WriteListCount({expr}.Count);")
                o.append(f"{ind}foreach (var item in {expr}) {cs_write_scalar(ctx, f.type, 'item')}")
            else:
                o.append(f"{ind}{cs_write_scalar(ctx, f.type, expr)}")
            if f.optional:
                o.append("            }")
        o.append("        }")
        o.append("")
        o.append(f"        public static {c.name} Read(ByteReader r)")
        o.append("        {")
        o.append(f"            var v = new {c.name}();")
        if c.has_optional:
            o.append("            uint mask = r.ReadU32();")
            nopt = sum(1 for f in c.fields if f.optional)
            if nopt < 32:
                o.append(f'            if ((mask >> {nopt}) != 0) throw new ProtocolException("unknown optional bits in {c.name}");')
        bit = 0
        for f in c.fields:
            name = pascal(f.name)
            ind = "            "
            if f.optional:
                o.append(f"            if ((mask & (1u << {bit})) != 0)")
                o.append("            {")
                ind = "                "
                bit += 1
            if f.is_list:
                o.append(f"{ind}int n_{f.name} = r.ReadListCount();")
                o.append(f"{ind}v.{name} = new List<{cs_base(ctx, f.type)}>(Math.Min(n_{f.name}, r.Remaining));")
                o.append(f"{ind}for (int i = 0; i < n_{f.name}; i++) v.{name}.Add({cs_read_scalar(ctx, f.type)});")
            else:
                o.append(f"{ind}v.{name} = {cs_read_scalar(ctx, f.type)};")
            if f.optional:
                o.append("            }")
        o.append("            return v;")
        o.append("        }")
        o.append("    }")
        o.append("")

    for s in structs:
        emit(s)
    for m in messages:
        emit(m)

    c2s = [m for m in messages if m.direction == "c2s"]
    s2c = [m for m in messages if m.direction == "s2c"]
    o.append("    public static class MessageCodec")
    o.append("    {")
    o.append('        public static string NameOf(ushort id)')
    o.append("        {")
    o.append("            switch (id)")
    o.append("            {")
    for m in messages:
        o.append(f'                case {m.msg_id}: return "{m.name}";')
    o.append('                default: return "Unknown";')
    o.append("            }")
    o.append("        }")
    o.append("")
    for side, own, other in (("Client", c2s, s2c), ("Server", s2c, c2s)):
        o.append(f"        /// <summary>Decode one payload sent by the {'client' if side == 'Client' else 'server'}. Throws ProtocolException on bad data.</summary>")
        o.append(f"        public static IMessage Decode{side}(ushort id, ByteReader r)")
        o.append("        {")
        o.append("            IMessage m;")
        o.append("            switch (id)")
        o.append("            {")
        for m in own:
            o.append(f"                case {m.msg_id}: m = {m.name}.Read(r); break;")
        for m in other:
            o.append(f"                case {m.msg_id}:")
        if other:
            o.append(f'                    throw new ProtocolException("message " + id + " has the wrong direction");')
        o.append('                default: throw new ProtocolException("unknown message id " + id);')
        o.append("            }")
        o.append('            if (r.Remaining != 0) throw new ProtocolException("trailing bytes after message " + id);')
        o.append("            return m;")
        o.append("        }")
        o.append("")
    o.append("    }")
    o.append("")
    o.append("    /// <summary>Implement this on the client to receive every server message type.</summary>")
    o.append("    public interface IServerMessageHandler")
    o.append("    {")
    for m in s2c:
        o.append(f"        void Handle({m.name} message);")
    o.append("    }")
    o.append("")
    o.append("    public static class ServerMessageDispatcher")
    o.append("    {")
    o.append("        public static void Dispatch(IMessage message, IServerMessageHandler handler)")
    o.append("        {")
    o.append("            switch (message)")
    o.append("            {")
    for m in s2c:
        o.append(f"                case {m.name} x: handler.Handle(x); break;")
    o.append('                default: throw new ProtocolException("not a server message: " + message.Id);')
    o.append("            }")
    o.append("        }")
    o.append("    }")
    o.append("}")
    return "\n".join(o) + "\n"


def gen_cs_golden(ctx: Ctx, samples):
    o = [HEADER, "#nullable disable", "using System;", "using System.Collections.Generic;", "using WaW.Protocol;", "",
         "namespace WaW.Protocol.Tests", "{", "    public static class GoldenSamples", "    {",
         "        public sealed class Sample", "        {", "            public string Name;", "            public ushort Id;",
         "            public bool ClientToServer;", "            public string Hex;", "            public Func<IMessage> Make;", "        }", "",
         "        public static IReadOnlyList<Sample> All => new List<Sample>", "        {"]
    for m, value, hexstr in samples:
        o.append(f'            new Sample {{ Name = "{m.name}", Id = {m.msg_id}, ClientToServer = {"true" if m.direction == "c2s" else "false"}, Hex = "{hexstr}",')
        o.append(f"                Make = () => {cs_composite_literal(ctx, m, value)} }},")
    o += ["        };", "    }", "}"]
    return "\n".join(o) + "\n"


# ------------------------------------------------------------------------------------------------ main

def main(argv):
    check = "--check" in argv
    meta, enums, structs, messages = load_schema(SCHEMA)
    ctx = Ctx(enums, structs)
    samples = []
    for m in messages:
        value = sample_composite(ctx, m, m.msg_id)
        samples.append((m, value, encode_composite(ctx, m, value).hex()))
    hpp, cpp = gen_cpp(meta, enums, structs, messages)
    outputs = {
        OUT_CPP_HPP: hpp,
        OUT_CPP_CPP: cpp,
        OUT_CPP_GOLDEN: gen_cpp_golden(ctx, samples),
        OUT_CS: gen_cs(meta, enums, structs, messages),
        OUT_CS_GOLDEN: gen_cs_golden(ctx, samples),
        OUT_VECTORS: json.dumps({"protocol_version": meta["protocol_version"],
                                 "samples": [{"name": m.name, "id": m.msg_id, "dir": m.direction, "hex": h} for m, _, h in samples]},
                                indent=2) + "\n",
    }
    stale = []
    for path, text in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    for p in stale:
        print(("STALE " if check else "wrote ") + str(p.relative_to(ROOT)))
    if check and stale:
        return 1
    if not stale:
        print("protocol outputs are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
