#include <doctest/doctest.h>

#include <bit>
#include <format>
#include <fstream>
#include <sstream>

#include <nlohmann/json.hpp>

#include "sim_fixtures.hpp"
#include "waw/core/env.hpp"
#include "waw/sim/movement.hpp"

// The server's movement rules are the reference for the Unity client's prediction. This test runs the shared cases in
// Protocol/vectors/movement_cases.json and compares the results bit-for-bit with Protocol/vectors/movement.json, which the C#
// suite checks too. Regenerate after an intentional rule change: set WAW_WRITE_VECTORS=1 and run the tests once.

using namespace waw;

namespace {

std::string read(const std::string& path) {
    std::ifstream in(path, std::ios::binary);
    REQUIRE_MESSAGE(in.good(), "cannot open " << path);
    std::stringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

std::string bits(float f) { return std::format("0x{:08x}", std::bit_cast<std::uint32_t>(f)); }

}  // namespace

TEST_CASE("movement matches the shared vectors bit for bit") {
    const std::string dir = std::string(WAW_PROTOCOL_ROOT) + "/vectors/";
    const auto cases = nlohmann::json::parse(read(dir + "movement_cases.json"));
    const auto db = test::fixture_content();

    nlohmann::json results = nlohmann::json::array();
    for (const auto& c : cases.at("cases")) {
        const auto rows = c.at("map").get<std::string>();
        const auto map = sim::TileMap::build(test::fixture_map(db, cases.at("maps").at(rows).get<std::vector<std::string>>()), db);
        sim::movement::MoverState s;
        s.position = {c.at("start")[0].get<float>(), c.at("start")[1].get<float>()};
        const int speed = c.at("speed").get<int>();
        for (const auto& step : c.at("steps")) {
            const auto dir_vec = sim::movement::direction_from_input(static_cast<std::int8_t>(step[0].get<int>()),
                                                                    static_cast<std::int8_t>(step[1].get<int>()));
            const auto dt = static_cast<float>(step[2].get<int>());
            const int repeat = step[3].get<int>();
            for (int i = 0; i < repeat; ++i) sim::movement::step(map, s, dir_vec, dt, speed);
        }
        results.push_back({{"name", c.at("name")},
                           {"x", s.position.x},
                           {"y", s.position.y},
                           {"sink", s.sink_level},
                           {"xBits", bits(s.position.x)},
                           {"yBits", bits(s.position.y)},
                           {"sinkBits", bits(s.sink_level)}});
    }

    const std::string out_path = dir + "movement.json";
    if (core::env("WAW_WRITE_VECTORS")) {
        std::ofstream out(out_path, std::ios::binary);
        out << nlohmann::json{{"comment", "Generated by Server/tests/test_movement_vectors.cpp from movement_cases.json - do not edit."},
                              {"results", results}}
                   .dump(2)
            << "\n";
        MESSAGE("wrote " << out_path);
        return;
    }
    const auto expected = nlohmann::json::parse(read(out_path)).at("results");
    REQUIRE(expected.size() == results.size());
    for (std::size_t i = 0; i < results.size(); ++i) {
        CAPTURE(results[i].at("name").get<std::string>());
        CHECK(results[i].at("xBits") == expected[i].at("xBits"));
        CHECK(results[i].at("yBits") == expected[i].at("yBits"));
        CHECK(results[i].at("sinkBits") == expected[i].at("sinkBits"));
    }
}
